Repository Ligator/timetrade, pull requests merged in 2023-05, with the labels that each got.

#1 Devise gem install
  Gemfile
  Gemfile.lock
  app/models/user.rb
  config/database.yml
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20230519041220_devise_create_users.rb
  db/schema.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: Complete

#3 Generate devise views
  app/controllers/application_controller.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
Labels: Complete

#2 FLY IO SETTINGS
  .dockerignore
  Dockerfile
  Gemfile
  Gemfile.lock
  bin/docker-entrypoint
  config/database.yml
  config/dockerfile.yml
  fly.toml
Labels: Complete

#4 Scaffold service
  app/controllers/services_controller.rb
  app/helpers/services_helper.rb
  app/models/service.rb
  app/views/services/_form.html.erb
  app/views/services/_service.html.erb
  app/views/services/_service.json.jbuilder
  app/views/services/edit.html.erb
  app/views/services/index.html.erb
  app/views/services/index.json.jbuilder
  app/views/services/new.html.erb
  app/views/services/show.html.erb
  app/views/services/show.json.jbuilder
  config/routes.rb
  db/migrate/20230519072154_create_services.rb
  db/migrate/20230519075717_add_active_to_services.rb
  db/schema.rb
  test/controllers/services_controller_test.rb
  test/fixtures/services.yml
  test/models/service_test.rb
  test/system/services_test.rb
Labels: incomplete

#6 Add task scaffold
  app/controllers/tasks_controller.rb
  app/helpers/tasks_helper.rb
  app/models/task.rb
  app/views/tasks/_form.html.erb
  app/views/tasks/_task.html.erb
  app/views/tasks/_task.json.jbuilder
  app/views/tasks/edit.html.erb
  app/views/tasks/index.html.erb
  app/views/tasks/index.json.jbuilder
  app/views/tasks/new.html.erb
  app/views/tasks/show.html.erb
  app/views/tasks/show.json.jbuilder
  config/routes.rb
  db/migrate/20230519090754_create_tasks.rb
  db/schema.rb
  test/controllers/tasks_controller_test.rb
  test/fixtures/tasks.yml
  test/models/task_test.rb
  test/system/tasks_test.rb
Labels: Complete

#12 Remove authenticity token
  app/controllers/application_controller.rb
Labels: Complete

#13 Add newrelic
  Gemfile
  Gemfile.lock
  config/newrelic.yml
Labels: Complete

#11 update form new registration
  app/views/devise/registrations/new.html.erb
  app/views/layouts/application.html.erb
Labels: 2 reviews

#14 User controller Generate
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/views/devise/registrations/edit.html.erb
  app/views/layouts/application.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  app/views/users/show.json.jbuilder
  config/routes.rb
  db/schema.rb
  test/controllers/users_controller_test.rb
Labels: 2 reviews

#16 groups of service
  app/controllers/services_controller.rb
  app/views/services/index.html.erb
  app/views/services/index.json.jbuilder
Labels: 1 review

#17 Remove task_id
  app/controllers/services_controller.rb
  app/views/services/_service.html.erb
  db/migrate/20230519072154_create_services.rb
  db/migrate/20230519083645_create_rankings.rb
  db/migrate/20230520000116_remove_column_task_id_from_table_services.rb
  db/schema.rb
  test/controllers/services_controller_test.rb
  test/fixtures/services.yml
  test/system/services_test.rb
Labels: 1 review

#18 Added model validations
  app/models/ranking.rb
  app/models/service.rb
  app/models/task.rb
  app/models/user.rb
Labels: 1 review

#19 Added user insights
  app/models/user.rb
  app/views/services/_service.json.jbuilder
  app/views/tasks/_task.json.jbuilder
  app/views/users/show.json.jbuilder
Labels: Complete

#20 Condition for create service rol
  app/controllers/services_controller.rb
Labels: 1 review

#21 Add url for services.json
  app/views/services/index.json.jbuilder
Labels: 1 review

#22 FIx condition service controller create
  app/controllers/services_controller.rb
  app/models/service.rb
  app/views/services/_service.json.jbuilder
  app/views/services/show.json.jbuilder
Labels: 1 review

#23 Tasks in show views
  app/controllers/services_controller.rb
  app/models/service.rb
  app/views/services/_service.json.jbuilder
  app/views/services/show.html.erb
Labels: 1 review

#25 Add bootstrap to view service show
  app/views/services/show.html.erb
  app/views/tasks/_form.html.erb
  app/views/tasks/_task.html.erb
Labels: incomplete
